version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    container_name: habit-tracker-db
    environment:
      POSTGRES_DB: habit-tracker-db
      POSTGRES_USER: habit-tracker-admin
      POSTGRES_PASSWORD: habittrackerpass123
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U habit-tracker-admin -d habit-tracker-db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - habit-tracker-network

  app:
    build:
      context: ..  # Changed to parent directory to access all modules
      dockerfile: habit-tracker-app/Dockerfile
    container_name: habit-tracker-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/habit-tracker-db
      - SPRING_DATASOURCE_USERNAME=habit-tracker-admin
      - SPRING_DATASOURCE_PASSWORD=habittrackerpass123
    ports:
      - "18080:8080"
    networks:
      - habit-tracker-network

volumes:
  postgres_data:
    name: habit-tracker-postgres-data

networks:
  habit-tracker-network:
    name: habit-tracker-network
    driver: bridge