version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    container_name: habit-tracker-db
    environment:
      POSTGRES_DB: ${DB_NAME:-habit-tracker-db}
      POSTGRES_USER: ${DB_USER:-habit-tracker-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-habittrackerpass123}
      PGDATA: ${PGDATA:-/var/lib/postgresql/data}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:${PGDATA:-/var/lib/postgresql/data}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER:-habit-tracker-admin} -d ${DB_NAME:-habit-tracker-db}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - habit-tracker-network
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: habit-tracker-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-dev}
      - DB_HOST=postgres
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME:-habit-tracker-db}
      - DB_USER=${DB_USER:-habit-tracker-admin}
      - DB_PASSWORD=${DB_PASSWORD:-habittrackerpass123}
    ports:
      - "${APP_PORT:-8080}:8080"
    networks:
      - habit-tracker-network
    restart: unless-stopped

volumes:
  postgres_data:
    name: habit-tracker-postgres-data

networks:
  habit-tracker-network:
    name: habit-tracker-network
    driver: bridge